version: '3.1'

services:  
    db:
        image: mysql:8.0
        restart: always
        cap_add:
          - SYS_NICE  # CAP_SYS_NICE
        ports:
          - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        command: mysqld --sql_mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_USER: mysql
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            
volumes:
    db_data: {}